name = "CSMP XII"
author = "CapivaraManca"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2d4309b4c2196b68f9fb4bad71ec08895dd0eef7c9d6dfdc273ac0bf7876f56"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
