general = {disable_mod = false, hide_bossbar = true, shadow_text = true, auto_start = false, animationSpeed = 1.0, always_show_ping = false, hide_debug_crosshair = false, background_color = 1867534416, space_modules = false, always_show_profiler = false, animations = true, fontScale = 1.0, hide_sidebar = true, always_show_tps = false}
[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	lines = {opengl_version = true, allocation_rate = true, display = true, java_version = true, gpu_driver = true, memory_usage = true, allocated_memory = true, cpu = true, gpu_utilization = true, time = true, gpu = true}
	enabled = true
[[modules_right]]
	name = "miscright"
	name_color = 16645526
	value_color = 5636095
	lines = {misc_right = true}
	enabled = false
[[modules_right]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_right]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	lines = {id_fluid = true, fluid_tags = false, block_states = true, targeted_block = false, block_tags = false, id_block = true, nothing = true, nothing2 = true, targeted_fluid = false, targeted_entity = true, fluid_states = false}
	enabled = true

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	lines = {minecraft = true}
	enabled = true
[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	lines = {fps = true}
	enabled = true
	color_low = 16733525
[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	lines = {shader = true, render_distance = true, graphics = true, clouds = true, biome_blend_radius = true}
	enabled = false
[[modules_left]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	lines = {server_tick = true, packets_sent = true, packets_received = true, tick_manager_status = true}
	enabled = false
[[modules_left]]
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	name = "coords"
	name_color = 16733525
	lines = {chunk_coords = true, player_coords = true, block_coords = true, absolute_velocity = false, velocity = false, chunk_relative_coords = true, horizontal_velocity = false}
	enabled = true
[[modules_left]]
	name = "chunks"
	chunks_disabled_color = 16733525
	name_color = 43775
	value_color = 16777045
	total_chunks_color = 16755200
	lines = {chunk_file = false, available_buffers = false, loaded_chunks_server = false, forceloaded_chunks = false, chunk_culling = false, pending_uploads = false, pending_chunks = false, loaded_chunks = false, spawn_chunks = false, client_chunk_cache = false, chunk_sections = false}
	chunks_enabled_color = 5635925
	enabled = false
[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	lines = {light = true, biome = true, rotation = true, facing = true, slime_chunk = true, local_difficulty = false, day_ticks = false, days_played = true, dimension = true, highest_block = false, highest_block_server = false, light_server = true}
	enabled = true
[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	lines = {entities = true, water_creature = false, underground_water_creature = false, ambient = false, particles = false, axolotls = false, creature = true, water_ambient = false, monster = true, misc = false}
	enabled = true
[[modules_left]]
	maximum_color = 43690
	name = "sound"
	name_color = 16755200
	value_color = 5636095
	lines = {ambient_sounds = true, sounds = true, mood = false}
	enabled = false
[[modules_left]]
	enabled_color = 5635925
	name = "help"
	name_color = 16645526
	value_color = 5636095
	disabled_color = 16733525
	lines = {help = true, fps_tps_new = true, ping = true, pie_graph_new = true}
	enabled = false
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	name = "miscleft"
	name_color = 16645526
	value_color = 5636095
	lines = {misc_left = true}
	enabled = false
